/**
 * W3C UI Events KeyboardEvent key attribute values
 * Based on: https://www.w3.org/TR/uievents-key/#named-key-attribute-values
 */

type Key = string;
type Editable = boolean;
export const SPECIAL_KEYS = new Map<Key, Editable>([["Unidentified", false]]);

export const MODIFIER_KEYS = new Map<Key, Editable>([
  ["Alt", false],
  ["AltGraph", false],
  ["CapsLock", false],
  ["Control", false],
  ["Fn", false],
  ["FnLock", false],
  ["Meta", false],
  ["NumLock", false],
  ["ScrollLock", false],
  ["Shift", false],
  ["Symbol", false],
  ["SymbolLock", false],
]);

export const LEGACY_MODIFIER_KEYS = new Map<Key, Editable>([
  ["Hyper", false],
  ["Super", false],
]);

export const WHITESPACE_KEYS = new Map<Key, Editable>([
  ["Enter", false],
  ["Tab", false],
  [" ", true],
]);

export const NAVIGATION_KEYS = new Map<Key, Editable>([
  ["ArrowDown", false],
  ["ArrowLeft", false],
  ["ArrowRight", false],
  ["ArrowUp", false],
  ["End", false],
  ["Home", false],
  ["PageDown", false],
  ["PageUp", false],
]);

export const EDITING_KEYS = new Map<Key, Editable>([
  ["Backspace", true],
  ["Clear", false],
  ["Copy", false],
  ["CrSel", false],
  ["Cut", false],
  ["Delete", true],
  ["EraseEof", false],
  ["ExSel", false],
  ["Insert", false],
  ["Paste", false],
  ["Redo", false],
  ["Undo", false],
]);

export const UI_KEYS = new Map<Key, Editable>([
  ["Accept", false],
  ["Again", false],
  ["Attn", false],
  ["Cancel", false],
  ["ContextMenu", false],
  ["Escape", false],
  ["Execute", false],
  ["Find", false],
  ["Help", false],
  ["Pause", false],
  ["Play", false],
  ["Props", false],
  ["Select", false],
  ["ZoomIn", false],
  ["ZoomOut", false],
]);

export const DEVICE_KEYS = new Map<Key, Editable>([
  ["BrightnessDown", false],
  ["BrightnessUp", false],
  ["Eject", false],
  ["LogOff", false],
  ["Power", false],
  ["PowerOff", false],
  ["PrintScreen", false],
  ["Hibernate", false],
  ["Standby", false],
  ["WakeUp", false],
]);

export const IME_COMPOSITION_KEYS = new Map<Key, Editable>([
  ["AllCandidates", false],
  ["Alphanumeric", false],
  ["CodeInput", false],
  ["Compose", false],
  ["Convert", false],
  ["Dead", false],
  ["FinalMode", false],
  ["GroupFirst", false],
  ["GroupLast", false],
  ["GroupNext", false],
  ["GroupPrevious", false],
  ["ModeChange", false],
  ["NextCandidate", false],
  ["NonConvert", false],
  ["PreviousCandidate", false],
  ["Process", false],
  ["SingleCandidate", false],
]);

export const KOREAN_KEYS = new Map<Key, Editable>([
  ["HangulMode", false],
  ["HanjaMode", false],
  ["JunjaMode", false],
]);

export const JAPANESE_KEYS = new Map<Key, Editable>([
  ["Eisu", false],
  ["Hankaku", false],
  ["Hiragana", false],
  ["HiraganaKatakana", false],
  ["KanaMode", false],
  ["KanjiMode", false],
  ["Katakana", false],
  ["Romaji", false],
  ["Zenkaku", false],
  ["ZenkakuHankaku", false],
]);

export const FUNCTION_KEYS = new Map<Key, Editable>([
  ["F1", false],
  ["F2", true],
  ["F3", false],
  ["F4", false],
  ["F5", false],
  ["F6", false],
  ["F7", false],
  ["F8", false],
  ["F9", false],
  ["F10", false],
  ["F11", false],
  ["F12", false],
  ["F13", false],
  ["F14", false],
  ["F15", false],
  ["F16", false],
  ["F17", false],
  ["F18", false],
  ["F19", false],
  ["F20", false],
  ["F21", false],
  ["F22", false],
  ["F23", false],
  ["F24", false],
  ["F25", false],
  ["F26", false],
  ["F27", false],
  ["F28", false],
  ["F29", false],
  ["F30", false],
  ["F31", false],
  ["F32", false],
  ["F33", false],
  ["F34", false],
  ["F35", false],
  ["Soft1", false],
  ["Soft2", false],
  ["Soft3", false],
  ["Soft4", false],
]);

export const PHONE_KEYS = new Map<Key, Editable>([
  ["AppSwitch", false],
  ["Call", false],
  ["Camera", false],
  ["CameraFocus", false],
  ["EndCall", false],
  ["GoBack", false],
  ["GoHome", false],
  ["HeadsetHook", false],
  ["LastNumberRedial", false],
  ["Notification", false],
  ["MannerMode", false],
  ["VoiceDial", false],
]);

export const MULTIMEDIA_KEYS = new Map<Key, Editable>([
  ["ChannelDown", false],
  ["ChannelUp", false],
  ["MediaFastForward", false],
  ["MediaPause", false],
  ["MediaPlay", false],
  ["MediaPlayPause", false],
  ["MediaRecord", false],
  ["MediaRewind", false],
  ["MediaStop", false],
  ["MediaTrackNext", false],
  ["MediaTrackPrevious", false],
]);

export const AUDIO_CONTROL_KEYS = new Map<Key, Editable>([
  ["AudioBalanceLeft", false],
  ["AudioBalanceRight", false],
  ["AudioBassDown", false],
  ["AudioBassBoost", false],
  ["AudioBassUp", false],
  ["AudioFaderFront", false],
  ["AudioFaderRear", false],
  ["AudioSurroundModeNext", false],
  ["AudioTrebleDown", false],
  ["AudioTrebleUp", false],
  ["AudioVolumeDown", false],
  ["AudioVolumeMute", false],
  ["AudioVolumeUp", false],
  ["MicrophoneToggle", false],
  ["MicrophoneVolumeDown", false],
  ["MicrophoneVolumeMute", false],
  ["MicrophoneVolumeUp", false],
]);

export const TV_KEYS = new Map<Key, Editable>([
  ["TV", false],
  ["TV3DMode", false],
  ["TVAntennaCable", false],
  ["TVAudioDescription", false],
  ["TVAudioDescriptionMixDown", false],
  ["TVAudioDescriptionMixUp", false],
  ["TVContentsMenu", false],
  ["TVDataService", false],
  ["TVInput", false],
  ["TVInputComponent1", false],
  ["TVInputComponent2", false],
  ["TVInputComposite1", false],
  ["TVInputComposite2", false],
  ["TVInputHDMI1", false],
  ["TVInputHDMI2", false],
  ["TVInputHDMI3", false],
  ["TVInputHDMI4", false],
  ["TVInputVGA1", false],
  ["TVMediaContext", false],
  ["TVNetwork", false],
  ["TVNumberEntry", false],
  ["TVPower", false],
  ["TVRadioService", false],
  ["TVSatellite", false],
  ["TVSatelliteBS", false],
  ["TVSatelliteCS", false],
  ["TVSatelliteToggle", false],
  ["TVTerrestrialAnalog", false],
  ["TVTerrestrialDigital", false],
  ["TVTimer", false],
]);

export const MEDIA_CONTROLLER_KEYS = new Map<Key, Editable>([
  ["AVRInput", false],
  ["AVRPower", false],
  ["ColorF0Red", false],
  ["ColorF1Green", false],
  ["ColorF2Yellow", false],
  ["ColorF3Blue", false],
  ["ColorF4Grey", false],
  ["ColorF5Brown", false],
  ["ClosedCaptionToggle", false],
  ["Dimmer", false],
  ["DisplaySwap", false],
  ["DVR", false],
  ["Exit", false],
  ["FavoriteClear0", false],
  ["FavoriteClear1", false],
  ["FavoriteClear2", false],
  ["FavoriteClear3", false],
  ["FavoriteRecall0", false],
  ["FavoriteRecall1", false],
  ["FavoriteRecall2", false],
  ["FavoriteRecall3", false],
  ["FavoriteStore0", false],
  ["FavoriteStore1", false],
  ["FavoriteStore2", false],
  ["FavoriteStore3", false],
  ["Guide", false],
  ["GuideNextDay", false],
  ["GuidePreviousDay", false],
  ["Info", false],
  ["InstantReplay", false],
  ["Link", false],
  ["ListProgram", false],
  ["LiveContent", false],
  ["Lock", false],
  ["MediaApps", false],
  ["MediaAudioTrack", false],
  ["MediaLast", false],
  ["MediaSkipBackward", false],
  ["MediaSkipForward", false],
  ["MediaStepBackward", false],
  ["MediaStepForward", false],
  ["MediaTopMenu", false],
  ["NavigateIn", false],
  ["NavigateNext", false],
  ["NavigateOut", false],
  ["NavigatePrevious", false],
  ["NextFavoriteChannel", false],
  ["NextUserProfile", false],
  ["OnDemand", false],
  ["Pairing", false],
  ["PinPDown", false],
  ["PinPMove", false],
  ["PinPToggle", false],
  ["PinPUp", false],
  ["PlaySpeedDown", false],
  ["PlaySpeedReset", false],
  ["PlaySpeedUp", false],
  ["RandomToggle", false],
  ["RcLowBattery", false],
  ["RecordSpeedNext", false],
  ["RfBypass", false],
  ["ScanChannelsToggle", false],
  ["ScreenModeNext", false],
  ["Settings", false],
  ["SplitScreenToggle", false],
  ["STBInput", false],
  ["STBPower", false],
  ["Subtitle", false],
  ["Teletext", false],
  ["VideoModeNext", false],
  ["Wink", false],
  ["ZoomToggle", false],
]);

export const SPEECH_KEYS = new Map<Key, Editable>([
  ["SpeechCorrectionList", false],
  ["SpeechInputToggle", false],
]);

export const DOCUMENT_KEYS = new Map<Key, Editable>([
  ["Close", false],
  ["New", false],
  ["Open", false],
  ["Print", false],
  ["Save", false],
  ["SpellCheck", false],
  ["MailForward", false],
  ["MailReply", false],
  ["MailSend", false],
]);

export const APPLICATION_SELECTOR_KEYS = new Map<Key, Editable>([
  ["LaunchCalculator", false],
  ["LaunchCalendar", false],
  ["LaunchContacts", false],
  ["LaunchMail", false],
  ["LaunchMediaPlayer", false],
  ["LaunchMusicPlayer", false],
  ["LaunchMyComputer", false],
  ["LaunchPhone", false],
  ["LaunchScreenSaver", false],
  ["LaunchSpreadsheet", false],
  ["LaunchWebBrowser", false],
  ["LaunchWebCam", false],
  ["LaunchWordProcessor", false],
  ["LaunchApplication1", false],
  ["LaunchApplication2", false],
  ["LaunchApplication3", false],
  ["LaunchApplication4", false],
  ["LaunchApplication5", false],
  ["LaunchApplication6", false],
  ["LaunchApplication7", false],
  ["LaunchApplication8", false],
  ["LaunchApplication9", false],
  ["LaunchApplication10", false],
  ["LaunchApplication11", false],
  ["LaunchApplication12", false],
  ["LaunchApplication13", false],
  ["LaunchApplication14", false],
  ["LaunchApplication15", false],
  ["LaunchApplication16", false],
]);

export const BROWSER_CONTROL_KEYS = new Map<Key, Editable>([
  ["BrowserBack", false],
  ["BrowserFavorites", false],
  ["BrowserForward", false],
  ["BrowserHome", false],
  ["BrowserRefresh", false],
  ["BrowserSearch", false],
  ["BrowserStop", false],
]);

export const NUMERIC_KEYPAD_KEYS = new Map<Key, Editable>([
  ["Decimal", false],
  ["Key11", false],
  ["Key12", false],
  ["Multiply", false],
  ["Add", false],
  ["Divide", false],
  ["Subtract", false],
  ["Separator", false],
]);

export const ALL_KEY_ATTRIBUTE_VALUES = new Map<Key, Editable>([
  ...SPECIAL_KEYS,
  ...MODIFIER_KEYS,
  ...LEGACY_MODIFIER_KEYS,
  ...WHITESPACE_KEYS,
  ...NAVIGATION_KEYS,
  ...EDITING_KEYS,
  ...UI_KEYS,
  ...DEVICE_KEYS,
  ...IME_COMPOSITION_KEYS,
  ...KOREAN_KEYS,
  ...JAPANESE_KEYS,
  ...FUNCTION_KEYS,
  ...PHONE_KEYS,
  ...MULTIMEDIA_KEYS,
  ...AUDIO_CONTROL_KEYS,
  ...TV_KEYS,
  ...MEDIA_CONTROLLER_KEYS,
  ...SPEECH_KEYS,
  ...DOCUMENT_KEYS,
  ...APPLICATION_SELECTOR_KEYS,
  ...BROWSER_CONTROL_KEYS,
  ...NUMERIC_KEYPAD_KEYS,
]);
export function isEditableKey(key: Key): boolean {
  const isValidKey = ALL_KEY_ATTRIBUTE_VALUES.get(key);
  if (isValidKey === undefined) {
    return true;
  }
  return isValidKey;
}
